package org.itstep.telegrambot.command;

public enum Command {
    NONE, NOTFORME,

    REGISTER, REGISTER_USER, REGISTER_ADMIN,
    NOTIFY, START, HELP, ABOUT_ME, USERS, TICKET, CLOSE_TICKET,
    CHAT_ID, SEND_TO_CHANNEL, SEND_TO_DISCUSS
}
